### ISSUE TITLE
quick review

### ISSUE THREAD

**Issue by Helias** [Gangelo99/Spotigram_bot-DMI_QD#18]
- copiate la github action dalla repository [qd-starter-pack](https://github.com/UNICT-Quality-Development/qd-starter-pack/)
- requirements_dev.txt deve contenere le dipendenze di "development", quindi quei software che servono per lo sviluppo dei test, come pytest e pytest-mock, mentre requirements.txt deve contenere i pacchetti che fanno funzionare il software a prescindere dai pyTelegramBotApi

**Comment by Gangelo99** [comment]
Garzie ancora @Helias, ma per la GitHub action cosa intendi?

**Comment by Helias** [comment]
La CI/CD, la pipeline, quel software che fa delle analisi statiche al software ogni volta che crei una pull request o che pushi un commit.

Tra le "analisi statiche" c'è anche una parte di software che esegue i test https://github.com/UNICT-Quality-Development/qd-starter-pack/blob/main/.github/workflows/ci.yml 

esempio:

https://github.com/UNICT-Quality-Development/qd-starter-pack/pull/21

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/519778/196962853-1fb0477f-e7a8-4a60-950f-f5d1af9c24d6.png">

Details: https://github.com/UNICT-Quality-Development/qd-starter-pack/actions/runs/2448986316/jobs/3722097835
